version: '3'
services:
  telegraf:
    image: telegraf:1.9.2-alpine
    environment:
      - TZ=Europe/Paris
    # ports:
    #   - 9273:9273
    restart: always
    volumes:
      - $PWD/telegraf/configuration/telegraf.conf:/etc/telegraf/telegraf.conf:ro
  prometheus:
    image: prom/prometheus:v2.6.0
    depends_on:
      - telegraf
    environment:
      - TZ=Europe/Paris
    # ports:
    #   - 9090:9090
    restart: always
    volumes:
      - $PWD/prometheus/configuration/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
  grafana:
    build:
      context: grafana
      dockerfile: Dockerfile
    depends_on:
      - prometheus
    environment:
      - TZ=Europe/Paris
      - GF_SECURITY_ADMIN_PASSWORD
      - GF_SECURITY_DISABLE_GRAVATAR=true
      - GF_ANALYTICS_REPORTING_ENABLED=false
      - GF_SNAPSHOTS_EXTERNAL_ENABLED=false
      - GF_AUTH_ANONYMOUS_ENABLED=true
    ports:
      - 3000:3000
    restart: always
    volumes:
      - grafana-data:/var/lib/grafana
volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local
