{
 "title": "Dockerhub Statistics",
 "tags": [
  "docker",
  "prometheus",
  "telegraf",
  "grafana"
 ],
 "time": { "from": "now/M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(dockerhub_status,namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "egaillardon/jmeter-plugins",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "dockerhub_pull_count{namespace=\"$namespace\",name=\"jmeter-plugins\"}"
    }
   ]
  },
  {
   "title": "Pulls",
   "type": "graph",
   "gridPos": { "h": 15, "w": 10, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dockerhub_pull_count{namespace=\"$namespace\"}",
     "legendFormat": "{{namespace}}/{{name}}"
    }
   ]
  },
  {
   "title": "Stars",
   "type": "graph",
   "gridPos": { "h": 15, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dockerhub_star_count{namespace=\"$namespace\"}",
     "legendFormat": "{{namespace}}/{{name}}"
    }
   ]
  },
  {
   "title": "egaillardon/jmeter",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "dockerhub_pull_count{namespace=\"$namespace\",name=\"jmeter\"}"
    }
   ]
  },
  {
   "title": "egaillardon/haggar",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 10 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "dockerhub_pull_count{namespace=\"$namespace\",name=\"haggar\"}"
    }
   ]
  }
 ]
}